# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'musicAlbums' do
 
 pod 'SwiftyJSON'
 pod 'Alamofire', '~> 4.3'
 pod 'AlamofireImage', '~> 3.1'
end
