# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'musicAlbums' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for musicAlbums

  target 'musicAlbumsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'musicAlbumsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
